name: Build Portfolio
on:
  push:
    tags:
      - "**"
  workflow_dispatch:
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - name: get the code
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node_version: 18
      - name: npm install
        run: npm install
      - name: npm build
        run: npm run build
      - name: rename dist to www
        run: mv ./dist ./www
      - name: get the dist file into an artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: www
          path: ./www
      - name: upload to ftp server
        uses: sokuhatiku/ftp-upload-artifact@v1
        with:
          name: upload
          path: ./www
          host: ftp.duve3138.odns.fr
          port: 21
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          secure: false
          remote-path: /