name: Build Portfolio
on:
  push:
    tags:
      - "**"
  workflow_dispatch:
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - name: get the code
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node_version: 18
      - name: npm install
        run: |
          npm install
          npm run build
      - name: get the dist file into an artifact
        uses: actions/upload-pages-artifact@v3
        with:
         name: portfolio
         path: ./dist
      - name: Upload to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.cluster029.hosting.ovh.net
          username:  ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: /www/
          port: 21